duckdb_profile:
  target: dev
  outputs:
    dev:
      path: /tmp/dbt.duckdb
      type: duckdb
snowflake_profile:
  outputs:
    dev:
      type: snowflake
      account: ADMIRALPIONEER-TOOLBOX
      user: sandbox
      private_key_path: /usr/local/airflow/dbt/snowflake_key.p8
      role: sandbox_admin
      warehouse: sandbox_wh
      database: sandbox_db
      schema: jaffle_shop_dev
      threads: 1